### ISSUE TITLE
[HIGH PRIORITY] Uploading too large of a logo causes server crash (HTTP 502)

### ISSUE THREAD

**Issue by ethamitc** [statuspal/statuspal#4]
So basically, I was setting up a status page, influxllc.statuspal.io. And I uploaded our logo (which is like 4000x4000 and Hi-Res) and took down your Ubuntu server by myself... http://prntscr.com/ka3uek

**Comment by messutied** [comment]
Hi @ethamitc, thanks for pointing that out we'll look into the issue, the site is up again.

**Comment by messutied** [comment]
This was fixed some time ago.
