### ISSUE TITLE
[Question] API + uptimerobot/other

### ISSUE THREAD

**Issue by mrc4tt** [statuspal/statuspal#5]
Hi.

Is it possible to running the "statuspal" on own server, with possible for APIv2 for uptimerobot (automatic update) and webhooks for post on discord/incl twitter?

**Comment by messutied** [comment]
Hi @MikkelDK, not we currently don't support uptime robot integration, but it's in the pipeline, although it'll ship much earlier to the hosted version of Statuspal, as don't have much resources to support the open source fork.

I don't fully understand the webhooks question, you mean statuspal would call a webhook when an incident is created/updated?

**Comment by mrc4tt** [comment]
> I don't fully understand the webhooks question, you mean statuspal would call a webhook when an incident is created/updated?

Correct @messutied

**Comment by messutied** [comment]
OK that's also in the pipeline, should arrive before the end of the year to hosted Statuspal, but can't give an ETA for the self-hosted edition unfortunately.

Closing the ticket as I think I've answered both questions.

**Comment by mrc4tt** [comment]
Hi, @messutied I would like to +up this.

Any planned for webhooks?
